version: "3.5"

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/Users/giacomofulvi/data/wordpress' # cambiare
  mariadb:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '/Users/giacomofulvi/data/mariadb' # cambiare


networks:
  inception:
    driver: bridge
